name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: gopath/github.com/katydid/parser-go
    - name: Checkout testsuite
      uses: actions/checkout@v4
      with:
        repository: katydid/testsuite
        path: gopath/github.com/katydid/testsuite
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23
    - name: Fetch dependencies
      run: |
        cd gopath/github.com/katydid/parser-go
        go mod download -x
    - name: Install tools
      run: |
        cd gopath/github.com/katydid/parser-go
        go install -x github.com/awalterschulze/checklicense
    - name: env
      run: env && go env && pwd
    - name: tree
      run: tree
    - name: Build
      run: |
        cd gopath/github.com/katydid/parser-go
        make build
    - name: Test
      run: |
        cd gopath/github.com/katydid/parser-go
        make test
    - name: Checklicencse
      run: |
        cd gopath/github.com/katydid/parser-go
        make checklicense
    - name: Diff
      run: |
        cd gopath/github.com/katydid/parser-go
        make diff
